import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, String, Boolean, Text, Float
from sqlalchemy.dialects.postgresql import UUID

from database.session import Base

"""
Wellness Content Database Model Module

This module defines the SQLAlchemy model for storing generated wellness content in the database.
It provides storage for content, metadata, and posting information.
"""


class WellnessContent(Base):
    """SQLAlchemy model for storing generated wellness content.

    This model stores wellness content generated by the AI along with metadata
    about the content type, target channel, and posting status.

    Attributes:
        id: UUID primary key, auto-generated
        content: The generated wellness content text
        content_type: The type of wellness content (meditation tip, weekly challenge, etc.)
        channel_id: The Discord channel ID where the content should be posted
        posted: Whether the content has been posted to Discord
        posted_at: Timestamp when the content was posted
        created_at: Timestamp of content creation
        updated_at: Timestamp of last update
    """

    __tablename__ = "wellness_content"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid1,
        doc="Unique identifier for the wellness content",
    )

    content = Column(Text, nullable=False, doc="The generated wellness content text")

    content_type = Column(
        String(50),
        nullable=False,
        doc="The type of wellness content (meditation tip, weekly challenge, etc.)",
    )

    channel_id = Column(
        String(20),
        nullable=False,
        doc="The Discord channel ID where the content should be posted",
    )

    posted = Column(
        Boolean, default=False, doc="Whether the content has been posted to Discord"
    )

    posted_at = Column(
        DateTime, nullable=True, doc="Timestamp when the content was posted"
    )

    reasoning = Column(
        Text, nullable=True, doc="The reasoning behind the generated content"
    )

    confidence = Column(
        Float, nullable=True, doc="Confidence score for the quality of the content"
    )

    created_at = Column(
        DateTime, default=datetime.now, doc="Timestamp when the content was created"
    )

    updated_at = Column(
        DateTime,
        default=datetime.now,
        onupdate=datetime.now,
        doc="Timestamp when the content was last updated",
    )
